//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finansai.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Santaupos
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Grynais { get; set; }
        public decimal MKorteleDnB { get; set; }
        public decimal JKorteleDanske { get; set; }
        public decimal JKortelėSwedBank { get; set; }
        public decimal JKortelėDnB { get; set; }
        public decimal Automobiliui { get; set; }
        public decimal Kelionei { get; set; }
        public decimal ForceMajor { get; set; }
        public decimal Sveikata { get; set; }
        public decimal Rubai { get; set; }
    }
}
