//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finansai.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportas
    {
        public int Id { get; set; }
        public int MetaiId { get; set; }
        public int MenuoId { get; set; }
        public int SavaiteId { get; set; }
        public int DienaId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public decimal MašinosPrieziura { get; set; }
        public decimal AutobusoTaksiIslaidos { get; set; }
        public decimal Draudimas { get; set; }
        public decimal Kuras { get; set; }
        public decimal Plovimas { get; set; }
        public decimal Kita { get; set; }
    
        public virtual Dienos Dienos { get; set; }
        public virtual Menesiai Menesiai { get; set; }
        public virtual Metai Metai { get; set; }
        public virtual Savaites Savaites { get; set; }
    }
}
